import randomstring from 'randomstring'
import { ConfigObject } from './config.controller'
import { Document } from '../entities/document.entity'
import { Repository } from 'typeorm'

export class DocumentHandler {
  private options: ConfigObject
  private repository: Repository<Document>

  constructor (options: ConfigObject, docsRepo: Repository<Document>) {
    this.options = options
    this.repository = docsRepo
  }

  /*
   * Calls `randomstring.generate` until it finds a unique id for the document
   */
  private createID (): string {
    return randomstring.generate(this.options.idLength)
  }

  /*
   * Creates a connection to the database, then creates a new entry in the database consisting of:
   *  - Document ID, generated by the createID() function
   *  - Document content, provided by arguments
   */
  async newDocument (content: string): Promise<object> {
    const id = this.createID()

    const doc = this.repository.create({
      id,
      content
    })

    this.repository.save(doc)

    return { ...doc }
  }

  async getDocument (id: string): Promise<Document | undefined> {
    const doc = await this.repository.findOne({
      where: { id }
    })

    return doc
  }
}
