import randomstring from 'randomstring'
import { ConfigObject } from './config.controller'
import { Document } from '../entities/document.entity'
import { Repository } from 'typeorm'

export class DocumentHandler {
  private options: ConfigObject
  // repository of documents (see: https://typeorm.io/#/working-with-repository)
  private repository: Repository<Document>

  constructor (options: ConfigObject, docsRepo: Repository<Document>) {
    this.options = options
    this.repository = docsRepo
  }

  private createID (): string {
    return randomstring.generate(this.options.idLength || 12)
  }

  private chooseID (): Promise<string> { // runs until a unique id is generated
    let id = this.createID()

    return new Promise((resolve) => {
      const doc = this.getDocument(id)

      doc.then(doc => {
        if (!doc /* references local doc */) { // if doc with id does not exist resolve
          resolve(id)
        } else { // otherwise gen new id and re-call function
          id = this.createID()
          this.chooseID()
        }
      })
    })
  }

  /**
    * Inserts a new document into the database with:
    *   - value of `content`
    *   - an ID generated by `createID()`
    *
    * @param content - Content to insert into database
    *
    * @returns Inserted document
    */
  async newDocument (content: string): Promise<object> {
    const id = await this.chooseID()

    const doc = this.repository.create({
      id,
      content
    })

    this.repository.save(doc)

    return { ...doc }
  }

  /**
   * Searches the database for a document with `ID`
   *
   * @param id - ID of document to get
   * @returns document if exists, otherwise `undefined`
   */
  async getDocument (id: string): Promise<Document | undefined> {
    const doc = await this.repository.findOne({
      where: { id }
    })

    return doc
  }
}
